### ISSUE TITLE
Library needs updated - Apple privacy manifest updated in 17.0.2 - App Store rejection

### ISSUE THREAD

**Issue by viswanath-pamarthi** [nicobarengo/Intercom.iOS#1]
Hi @nicobarengo ,

Starting May 1st Apple App Store will reject the apps for required reasons api, I see intercom updated/corrected to remove one of the required reasons api in version 17.0.2, Can you please update the library as soon as possible to 17.0.2, to help prevent App Store rejection of the apps using your library ?

https://community.intercom.com/mobile-sdks-24/missing-required-reason-for-accessing-file-timestamp-in-ios-sdk-privacy-manifest-6985

https://github.com/intercom/intercom-ios/releases/tag/17.0.2

https://developer.apple.com/news/?id=pvszzano#:~:text=Starting%20May%201%2C%202024%2C%20new,Privacy%20manifests

Thanks,
Viswanath

**Comment by nicobarengo** [comment]
Hi @viswanath-pamarthi, I will look into it as soon as I can as I will be affected as well. 
Thanks for bring it up...

**Comment by viswanath-pamarthi** [comment]
@nicobarengo  Thank you

**Comment by nicobarengo** [comment]
Fixed in 17.0.3

**Comment by viswanath-pamarthi** [comment]
@nicobarengo 
Appreciate your quick response, I just noticed that your latest release targets iOS framework: net8.0-ios17.2. However, your previous version target net8.0-ios17.0 . We are targetting net8.0-ios17.0 in our app and this makes the latest release incompatible.

![image](https://github.com/nicobarengo/Intercom.iOS/assets/24984365/0740c0ba-5ad1-4264-9009-2f849785c554)

**Comment by nicobarengo** [comment]
It's builded against the last version of net8.0.  Try updating by running `sudo dotnet workload update` as there is nothing that breaks from iOS 17.0 to iOS 17.2

**Comment by viswanath-pamarthi** [comment]
Thanks @nicobarengo , unfortunately, I can't update right now, I will check what I need to do.
